name: EndOfLife-EN
version: '${project.version}'
main: de.mxscha.endernationendoflife.EndoflifeCore
api-version: 1.19

commands:
  setup:
  spawn:
  enderchest:
    aliases: ec
  backpack:
    aliases: bp
  gamemode:
  money:
  invsee:
  jobs: