name: EndOfLife-EN
version: '${project.version}'
main: de.mxscha.en.endoflife.EndoflifeCore
api-version: 1.19

commands:
  setup:
  spawn:
  enderchest:
    aliases: ec
  backpack:
    aliases: bp
  gamemode:
    aliases: gm
  money:
  invsee:
  jobs:
  build:
  vanish:
    aliases: v
  pay:
  tpa:
  tpaccept:
  trade:
  playerinfo:
  head:
  givekey:
  home:
  sethome:
  help: